export const types={
    ADD_USER: 'AUTHENTICATE_USER',
    ADD_USER_SUCCESS:'ADD_USER_SUCCESS',
    ADD_USER_ERROR:'ADD_USER_ERROR',
    DELETE_USER: 'DELETE_USER',
    DELETE_USER_SUCCESS:'ADD_USER_SUCCESS',
    DELETE_USER_ERROR:'ADD_USER_ERROR',
};